declare interface MapDispatchToListenRouteChange extends
MapHelperToDispatch,
MapWaitForServerToDispatch {}

declare interface ListenRouteChangeProps extends
MapDispatchToListenRouteChange,
WithRouterProps {}
