export {
  LOGIN_REGEXP,
  MAX_LOGIN_LENGTH,
  MAX_PASSWORD_LENGTH,
  MIN_LOGIN_LENGTH,
  MIN_PASSWORD_LENGTH,
  PASSWORD_REGEXP,
  SPECIAL_CHARACTERS,
} from '../common/constants';

export const HTML_CONVERSATION_ID = 'app-conversation';
